name: fate-10000
namespace: fate-10000
chartName: fate
chartVersion: v1.4.5
partyId: 10000
registry: ""
pullPolicy: 
persistence: false
istio:
  enabled: false
modules:
  - rollsite
  - clustermanager
  - nodemanager
  - mysql
  - python
  - client
  - spark

rollsite: 
  type: NodePort
  nodePort: 30010
  exchange:
    ip: 192.168.1.1
    port: 30000
  partyList:
  - partyId: 9999
    partyIp: 192.168.9.1
    partyPort: 30009
  nodeSelector: {}

nodemanager:
  count: 3
  sessionProcessorsPerNode: 4
  storageClass: "nodemanagers"
  accessMode: ReadWriteOnce
  size: 2Gi
  list:
  - name: nodemanager
    nodeSelector: {}
    sessionProcessorsPerNode: 4
    subPath: "nodemanager"
    existingClaim: ""
    storageClass: "nodemanager"
    accessMode: ReadWriteOnce
    size: 1Gi

python:
  fateflowType: NodePort
  fateflowNodePort: 30109
  nodeSelector: {}

mysql: 
  nodeSelector: {}
  ip: mysql
  port: 3306
  database: eggroll_meta
  user: fate
  password: fate_dev
  subPath: ""
  existingClaim: ""
  storageClass: "mysql"
  accessMode: ReadWriteOnce
  size: 1Gi

#
#externalMysqlIp: mysql
#externalMysqlPort: 3306
#externalMysqlDatabase: eggroll_meta
#externalMysqlUser: fate
#externalMysqlPassword: fate_dev


servingIp: 192.168.9.1
servingPort: 30209


spark:
  master:
    Image: "bde2020/spark-master"
    ImageTag: "2.4.1-hadoop2.7"
    replicas: 1
    nodeSelector: {}
  worker:
    Image: "bde2020/spark-worker"
    ImageTag: "2.4.1-hadoop2.7"
    replicas: 1
    nodeSelector: {}
hdfs:
  namenode:
    nodeSelector: {}
  datanode:
    nodeSelector: {}
nginx:
  nodeSelector: {}
  route_table: 
    10000: 
      proxy: 
        - host: 192.168.0.1 
          port: 9390
      fateflow: 
        - host: 192.168.0.1
          port: 9360
rabbitmq:
  nodeSelector: {}
  route_table:
    10000:
      host: rabbitmq
      port: 5672
